version: '3.8'

services:
  # Backend service (agentapi-proxy)
  backend:
    image: ghcr.io/takutakahashi/agentapi-proxy:latest
    container_name: ccplant-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ccplant-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend service (agentapi-ui)
  frontend:
    image: ghcr.io/takutakahashi/agentapi-ui:latest
    container_name: ccplant-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - ccplant-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


networks:
  ccplant-network:
    driver: bridge

volumes:
  # Add volumes here if needed for persistent data