name: Release ccplant Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release-ccplant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION from tag: $TAG"

      - name: Get latest backend and frontend versions
        id: dependency_versions
        run: |
          # Get latest tag from backend repository
          BACKEND_TAG=$(gh api repos/takutakahashi/agentapi-proxy/releases/latest --jq '.tag_name')
          BACKEND_VERSION=${BACKEND_TAG#v}
          echo "backend_version=$BACKEND_VERSION" >> $GITHUB_OUTPUT
          echo "Latest backend version: $BACKEND_VERSION"
          
          # Get latest tag from frontend repository  
          FRONTEND_TAG=$(gh api repos/takutakahashi/agentapi-ui/releases/latest --jq '.tag_name')
          FRONTEND_VERSION=${FRONTEND_TAG#v}
          echo "frontend_version=$FRONTEND_VERSION" >> $GITHUB_OUTPUT
          echo "Latest frontend version: $FRONTEND_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update ccplant Chart.yaml version and dependencies
        run: |
          # Update ccplant chart version
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.version }}/" charts/ccplant/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ steps.version.outputs.version }}\"/" charts/ccplant/Chart.yaml
          
          # Update dependency versions (agentapi-proxy needs v prefix, agentapi-ui doesn't)
          sed -i '/name: agentapi-proxy/,/alias: backend/ s/version: ".*"/version: "v${{ steps.dependency_versions.outputs.backend_version }}"/' charts/ccplant/Chart.yaml
          sed -i '/name: agentapi-ui/,/alias: frontend/ s/version: ".*"/version: "${{ steps.dependency_versions.outputs.frontend_version }}"/' charts/ccplant/Chart.yaml
          
          echo "Updated ccplant Chart.yaml:"
          cat charts/ccplant/Chart.yaml

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.18.3'

      - name: Login to GitHub Container Registry for dependencies
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Update dependencies
        run: |
          cd charts/ccplant
          helm dependency update

      - name: Lint ccplant Helm chart
        run: |
          helm lint charts/ccplant/

      - name: Package ccplant Helm chart
        run: |
          helm package charts/ccplant/
          ls -la *.tgz

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push ccplant chart to OCI registry
        run: |
          CCPLANT_CHART=$(ls ccplant-*.tgz)
          echo "Pushing ccplant chart: $CCPLANT_CHART"
          helm push "$CCPLANT_CHART" oci://ghcr.io/${{ github.repository_owner }}/charts

      - name: Create release notes
        run: |
          cat > release-notes.md << EOF
          # ccplant Release ${{ steps.version.outputs.tag }}
          
          ## Installation
          
          \`\`\`bash
          helm install ccplant oci://ghcr.io/${{ github.repository_owner }}/charts/ccplant --version ${{ steps.version.outputs.version }}
          \`\`\`
          
          ## Upgrade
          
          \`\`\`bash
          helm upgrade ccplant oci://ghcr.io/${{ github.repository_owner }}/charts/ccplant --version ${{ steps.version.outputs.version }}
          \`\`\`
          
          ## Chart Information
          
          - **Chart Version**: ${{ steps.version.outputs.version }}
          - **App Version**: ${{ steps.version.outputs.version }}
          - **Registry**: ghcr.io/${{ github.repository_owner }}/charts/ccplant
          - **Backend Version**: ${{ steps.dependency_versions.outputs.backend_version }}
          - **Frontend Version**: ${{ steps.dependency_versions.outputs.frontend_version }}
          
          ## Components
          
          This chart deploys the complete ccplant stack including:
          - agentapi-proxy (backend)
          - agentapi-ui (frontend)
          
          ## Changes
          
          See the [changelog](CHANGELOG.md) for detailed changes in this release.
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.md
          files: |
            ccplant-*.tgz
          tag_name: ${{ steps.version.outputs.tag }}
          name: ccplant Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccplant-chart-${{ steps.version.outputs.version }}
          path: |
            ccplant-*.tgz
            release-notes.md
          retention-days: 30