name: Release ccplant Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release-ccplant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION from tag: $TAG"

      - name: Update ccplant Chart.yaml version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.version }}/" charts/ccplant/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ steps.version.outputs.version }}\"/" charts/ccplant/Chart.yaml
          echo "Updated ccplant Chart.yaml versions:"
          grep -E "^(version|appVersion):" charts/ccplant/Chart.yaml

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.18.3'

      - name: Update dependencies
        run: |
          cd charts/ccplant
          helm dependency update

      - name: Lint ccplant Helm chart
        run: |
          helm lint charts/ccplant/

      - name: Package ccplant Helm chart
        run: |
          helm package charts/ccplant/
          ls -la *.tgz

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push ccplant chart to OCI registry
        run: |
          CCPLANT_CHART=$(ls ccplant-*.tgz)
          echo "Pushing ccplant chart: $CCPLANT_CHART"
          helm push "$CCPLANT_CHART" oci://ghcr.io/${{ github.repository_owner }}/charts

      - name: Create release notes
        run: |
          cat > release-notes.md << EOF
          # ccplant Release ${{ steps.version.outputs.tag }}
          
          ## Installation
          
          \`\`\`bash
          helm install ccplant oci://ghcr.io/${{ github.repository_owner }}/charts/ccplant --version ${{ steps.version.outputs.version }}
          \`\`\`
          
          ## Upgrade
          
          \`\`\`bash
          helm upgrade ccplant oci://ghcr.io/${{ github.repository_owner }}/charts/ccplant --version ${{ steps.version.outputs.version }}
          \`\`\`
          
          ## Chart Information
          
          - **Chart Version**: ${{ steps.version.outputs.version }}
          - **App Version**: ${{ steps.version.outputs.version }}
          - **Registry**: ghcr.io/${{ github.repository_owner }}/charts/ccplant
          - **Dependencies**: Uses latest agentapi-proxy and agentapi-ui OCI charts
          
          ## Components
          
          This chart deploys the complete ccplant stack including:
          - agentapi-proxy (backend)
          - agentapi-ui (frontend)
          
          ## Changes
          
          See the [changelog](CHANGELOG.md) for detailed changes in this release.
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.md
          files: |
            ccplant-*.tgz
          tag_name: ${{ steps.version.outputs.tag }}
          name: ccplant Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccplant-chart-${{ steps.version.outputs.version }}
          path: |
            ccplant-*.tgz
            release-notes.md
          retention-days: 30